-- MySQL Script generated by MySQL Workbench
-- Tue Enero 04 18:44:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbMyM
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbMyM
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbMyM` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `dbMyM` ;

-- -----------------------------------------------------
-- Table `dbMyM`.`propietario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbMyM`.`propietario` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(10) NULL DEFAULT NULL,
  `comentarios` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `dbMyM`.`tipomascota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbMyM`.`tipomascota` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `dbMyM`.`mascota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbMyM`.`mascota` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombreM` VARCHAR(45) NULL DEFAULT NULL,
  `tipomascota_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `propietario_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `mascota_tipomascota_id_foreign` (`tipomascota_id` ASC) ,
  INDEX `mascota_propietario_id_foreign` (`propietario_id` ASC) ,
  CONSTRAINT `mascota_propietario_id_foreign`
    FOREIGN KEY (`propietario_id`)
    REFERENCES `dbMyM`.`propietario` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `mascota_tipomascota_id_foreign`
    FOREIGN KEY (`tipomascota_id`)
    REFERENCES `dbMyM`.`tipomascota` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- INSERTAR DATOS QUEMADOS
-- -----------------------------------------------------
INSERT INTO propietario (nombre, direccion, telefono, comentarios ) VALUES ('David', 'Turbo', '8274567', 'Estudiante');
INSERT INTO propietario (nombre, direccion, telefono, comentarios ) VALUES ('Marcela', 'Apartado', '8268345', 'Profesora');
INSERT INTO propietario (nombre, direccion, telefono, comentarios ) VALUES ('Paola', 'Carepa', '8255678', 'Nada');
INSERT INTO propietario (nombre, direccion, telefono, comentarios ) VALUES ('Felipe', 'Turbo', '8271234', 'Deportes');
INSERT INTO propietario (nombre, direccion, telefono, comentarios ) VALUES ('Diego', 'Necocli', '8286703', 'viajar');

--
INSERT INTO tipomascota (descripcion) VALUES ('Perro');
INSERT INTO tipomascota (descripcion) VALUES ('Hanster');
INSERT INTO tipomascota (descripcion) VALUES ('Gato');
INSERT INTO tipomascota (descripcion) VALUES ('Loro');

--
INSERT INTO mascota (nombreM, tipomascota_id, propietario_id) VALUES ('Caro', '3', '3');
INSERT INTO mascota (nombreM, tipomascota_id, propietario_id) VALUES ('Lisin', '2', '4');
INSERT INTO mascota (nombreM, tipomascota_id, propietario_id) VALUES ('Lulu', '1', '1');
INSERT INTO mascota (nombreM, tipomascota_id, propietario_id) VALUES ('Cora', '1', '5');
INSERT INTO mascota (nombreM, tipomascota_id, propietario_id) VALUES ('Mechas', '4', '2');
-- -----------------------------------------------------

-- -----------------------------------------------------
-- CONSULTAS
-- -----------------------------------------------------
/*Listar todas las mascotas*/
SELECT  mascota.id, nombreM, tipomascota.descripcion 
FROM dbMyM.mascota
INNER JOIN dbMyM.tipomascota
ON  mascota.tipomascota_id = tipomascota.id ;

/* Listar las mascotas que no han sido adoptadas.*/
SELECT  mascota.id, nombreM, tipomascota.descripcion 
FROM dbMyM.mascota
LEFT JOIN dbMyM.tipomascota
ON  mascota.tipomascota_id = tipomascota.id 
LEFT JOIN dbMyM.propietario
ON  mascota.propietario_id = propietario.id 
WHERE mascota.propietario_id  IS NULL;

/*Listar el número de mascotas por cada tipo de mascota*/
SELECT DISTINCT tipomascota.*, COUNT(*) AS mascotas_cnt
FROM dbMyM.mascota m
    INNER JOIN dbMyM.tipomascota
ON m.tipomascota_id = tipomascota.id
GROUP BY tipomascota.id;
--
/*Listar los usuarios que tengan mas de 1 mascota*/
SELECT DISTINCT propietario.*, COUNT(*) AS mascotas_cnt
FROM dbMyM.mascota m
INNER JOIN dbMyM.propietario
ON m.propietario_id = propietario.id
    GROUP BY propietario.id
HAVING COUNT(mascotas_cnt) > 1; 
--
/*Listar el número de mascotas por cada tipo de mascota y por cada propietario.*/

SELECT DISTINCT tipomascota.*, propietario.*, COUNT(*) AS mascotas_cnt
FROM dbMyM.mascota m
LEFT JOIN dbMyM.tipomascot
ON m.tipomascota_id = tipomascota.id
LEFT JOIN dbMyM.propietario
ON  m.propietario_id = propietario.id 
WHERE  m.propietario_id = propietario.id 
GROUP BY  tipomascota.id 
ORDER BY tipomascota.id ASC ;
--
/*Listar los propietarios que no tienen mascotas.*/

SELECT DISTINCT propietario.id, propietario.nombre, propietario.comentarios 
FROM dbMyM.mascota  JOIN dbMyM.propietario
ON mascota.propietario_id  != propietario.id
ORDER BY propietario.id ASC;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;